tests: update include directory tests to support wildcard syntax.
Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

diff --git a/tests/shell/testcases/include/0005glob_empty_0 b/tests/shell/testcases/include/0005glob_empty_0
--- a/tests/shell/testcases/include/0005glob_empty_0
+++ b/tests/shell/testcases/include/0005glob_empty_0
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Including files in an empty directory must not fail.
+
 set -e
 
 tmpdir=$(mktemp -d)
@@ -8,7 +10,7 @@ if [ ! -d $tmpdir ] ; then
         exit 0
 fi
 
-tmpfile1=$(mktemp -p $tmpdir)
+tmpfile1=$(mktemp)
 if [ ! -w $tmpfile1 ] ; then
         echo "Failed to create tmp file" >&2
         exit 0
@@ -17,13 +19,13 @@ fi
 # cleanup if aborted
 trap "rm -rf $tmpfile1 && rmdir $tmpdir" EXIT
 
-RULESET1="include \"$tmpdir\""
+RULESET1="include \"$tmpdir/*\""
 
 echo "$RULESET1" > $tmpfile1
 
 $NFT -f $tmpfile1
 
-if [ $? -eq 0 ] ; then
-        echo "E: did not catch missing slash in directory name" >&2
+if [ $? -ne 0 ] ; then
+        echo "E: unable to load good ruleset" >&2
         exit 1
 fi
diff --git a/tests/shell/testcases/include/0010glob_broken_file_1 b/tests/shell/testcases/include/0010glob_broken_file_1
--- a/tests/shell/testcases/include/0010glob_broken_file_1
+++ b/tests/shell/testcases/include/0010glob_broken_file_1
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Loading broken files must fail.
+
 set -e
 
 tmpdir=$(mktemp -d)
@@ -8,15 +10,13 @@ if [ ! -d $tmpdir ] ; then
         exit 0
 fi
 
-tmpfile1="$tmpdir/01_file.nft"
-touch $tmpfile1
+tmpfile1=$(mktemp -p $tmpdir)
 if [ ! -w $tmpfile1 ] ; then
         echo "Failed to create tmp file" >&2
         exit 0
 fi
 
-tmpfile2="$tmpdir/02_file.nft"
-touch $tmpfile2
+tmpfile2=$(mktemp -p $tmpdir)
 if [ ! -w $tmpfile2 ] ; then
         echo "Failed to create tmp file" >&2
         exit 0
@@ -31,20 +31,19 @@ fi
 # cleanup if aborted
 trap "rm -rf $tmpfile1 $tmpfile2 $tmpfile3 && rmdir $tmpdir" EXIT
 
-# add interdependent rulesets
 RULESET1="add table x"
-RULESET2="add chain x y"
-RULESET3="include \"$tmpdir/\""
 
-# Note different order when compared with 0011dir_depencency_0. The idea
-# here is to introduce wrong order to get the loading fail.
-echo "$RULESET1" > $tmpfile2
-echo "$RULESET2" > $tmpfile1
+# do an error in a file
+RULESET2="intentionally broken file"
+RULESET3="include \"$tmpdir/*\""
+
+echo "$RULESET1" > $tmpfile1
+echo "$RULESET2" > $tmpfile2
 echo "$RULESET3" > $tmpfile3
 
 $NFT -f $tmpfile3
 
 if [ $? -eq 0 ] ; then
-        echo "E: did not catch wrong file order in include directory" >&2
+        echo "E: didn't catch a broken file in directory" >&2
         exit 1
 fi
diff --git a/tests/shell/testcases/include/0011glob_dependency_0 b/tests/shell/testcases/include/0011glob_dependency_0
--- a/tests/shell/testcases/include/0011glob_dependency_0
+++ b/tests/shell/testcases/include/0011glob_dependency_0
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Files are included in alphabetical order.
+
 set -e
 
 tmpdir=$(mktemp -d)
@@ -8,13 +10,15 @@ if [ ! -d $tmpdir ] ; then
         exit 0
 fi
 
-tmpfile1=$(mktemp -p $tmpdir)
+tmpfile1="$tmpdir/01_file.nft"
+touch $tmpfile1
 if [ ! -w $tmpfile1 ] ; then
         echo "Failed to create tmp file" >&2
         exit 0
 fi
 
-tmpfile2=$(mktemp -p $tmpdir)
+tmpfile2="$tmpdir/02_file.nft"
+touch $tmpfile2
 if [ ! -w $tmpfile2 ] ; then
         echo "Failed to create tmp file" >&2
         exit 0
@@ -29,11 +33,10 @@ fi
 # cleanup if aborted
 trap "rm -rf $tmpfile1 $tmpfile2 $tmpfile3 && rmdir $tmpdir" EXIT
 
+# add interdependent rulesets
 RULESET1="add table x"
-
-# do an error in a file
-RULESET2="intentionally broken file"
-RULESET3="include \"$tmpdir/\""
+RULESET2="add chain x y"
+RULESET3="include \"$tmpdir/*\""
 
 echo "$RULESET1" > $tmpfile1
 echo "$RULESET2" > $tmpfile2
@@ -41,7 +44,7 @@ echo "$RULESET3" > $tmpfile3
 
 $NFT -f $tmpfile3
 
-if [ $? -eq 0 ] ; then
-        echo "E: didn't catch a broken file in directory" >&2
+if [ $? -ne 0 ] ; then
+        echo "E: unable to load good ruleset" >&2
         exit 1
 fi
diff --git a/tests/shell/testcases/include/0012glob_dependency_1 b/tests/shell/testcases/include/0012glob_dependency_1
--- a/tests/shell/testcases/include/0012glob_dependency_1
+++ b/tests/shell/testcases/include/0012glob_dependency_1
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Files are included in alphabetical order.
+
 set -e
 
 tmpdir=$(mktemp -d)
@@ -34,15 +36,17 @@ trap "rm -rf $tmpfile1 $tmpfile2 $tmpfile3 && rmdir $tmpdir" EXIT
 # add interdependent rulesets
 RULESET1="add table x"
 RULESET2="add chain x y"
-RULESET3="include \"$tmpdir/\""
+RULESET3="include \"$tmpdir/*\""
 
-echo "$RULESET1" > $tmpfile1
-echo "$RULESET2" > $tmpfile2
+# Note different order when compared with 0011dir_depencency_0. The idea
+# here is to introduce wrong order to get the loading fail.
+echo "$RULESET1" > $tmpfile2
+echo "$RULESET2" > $tmpfile1
 echo "$RULESET3" > $tmpfile3
 
 $NFT -f $tmpfile3
 
-if [ $? -ne 0 ] ; then
-        echo "E: unable to load good ruleset" >&2
+if [ $? -eq 0 ] ; then
+        echo "E: did not catch wrong file order in include directory" >&2
         exit 1
 fi
